#ifndef DIO_CONFIG_H_
#define DIO_CONFIG_H_

/*
Configure pins direction:
    options:    1- INPUT
                2- OUTPUT
*/
//PORTA
#define PORTA_PIN0_DIRECTION      INPUT
#define PORTA_PIN1_DIRECTION      OUTPUT
#define PORTA_PIN2_DIRECTION      OUTPUT
#define PORTA_PIN3_DIRECTION      OUTPUT
#define PORTA_PIN4_DIRECTION      OUTPUT
#define PORTA_PIN5_DIRECTION      OUTPUT
#define PORTA_PIN6_DIRECTION      OUTPUT
#define PORTA_PIN7_DIRECTION      OUTPUT

//PORTB
#define PORTB_PIN0_DIRECTION      OUTPUT
#define PORTB_PIN1_DIRECTION      OUTPUT
#define PORTB_PIN2_DIRECTION      OUTPUT
#define PORTB_PIN3_DIRECTION      OUTPUT
#define PORTB_PIN4_DIRECTION      OUTPUT
#define PORTB_PIN5_DIRECTION      OUTPUT
#define PORTB_PIN6_DIRECTION      OUTPUT
#define PORTB_PIN7_DIRECTION      OUTPUT

//PORTC
#define PORTC_PIN0_DIRECTION      OUTPUT
#define PORTC_PIN1_DIRECTION      OUTPUT
#define PORTC_PIN2_DIRECTION      OUTPUT
#define PORTC_PIN3_DIRECTION      OUTPUT
#define PORTC_PIN4_DIRECTION      OUTPUT
#define PORTC_PIN5_DIRECTION      OUTPUT
#define PORTC_PIN6_DIRECTION      OUTPUT
#define PORTC_PIN7_DIRECTION      OUTPUT

//PORTD
#define PORTD_PIN0_DIRECTION      OUTPUT
#define PORTD_PIN1_DIRECTION      OUTPUT
#define PORTD_PIN2_DIRECTION      OUTPUT
#define PORTD_PIN3_DIRECTION      OUTPUT
#define PORTD_PIN4_DIRECTION      OUTPUT
#define PORTD_PIN5_DIRECTION      OUTPUT
#define PORTD_PIN6_DIRECTION      OUTPUT
#define PORTD_PIN7_DIRECTION      OUTPUT


/*
Configure initial value of pins, Options for input pins:    1- FLOATING
                                                            2- PULL_UP

                                Options for output pins:    1- HIGH
                                                            2- LOW
*/
//PORTA
#define PORTA_PIN0_INITIAL_VALUE      FLOATING
#define PORTA_PIN1_INITIAL_VALUE      LOW
#define PORTA_PIN2_INITIAL_VALUE      LOW
#define PORTA_PIN3_INITIAL_VALUE      LOW
#define PORTA_PIN4_INITIAL_VALUE      LOW
#define PORTA_PIN5_INITIAL_VALUE      LOW
#define PORTA_PIN6_INITIAL_VALUE      LOW
#define PORTA_PIN7_INITIAL_VALUE      LOW

//PORTB
#define PORTB_PIN0_INITIAL_VALUE      LOW
#define PORTB_PIN1_INITIAL_VALUE      LOW
#define PORTB_PIN2_INITIAL_VALUE      LOW
#define PORTB_PIN3_INITIAL_VALUE      LOW
#define PORTB_PIN4_INITIAL_VALUE      LOW
#define PORTB_PIN5_INITIAL_VALUE      LOW
#define PORTB_PIN6_INITIAL_VALUE      LOW
#define PORTB_PIN7_INITIAL_VALUE      LOW

//PORTC
#define PORTC_PIN0_INITIAL_VALUE      LOW
#define PORTC_PIN1_INITIAL_VALUE      LOW
#define PORTC_PIN2_INITIAL_VALUE      LOW
#define PORTC_PIN3_INITIAL_VALUE      LOW
#define PORTC_PIN4_INITIAL_VALUE      LOW
#define PORTC_PIN5_INITIAL_VALUE      LOW
#define PORTC_PIN6_INITIAL_VALUE      LOW
#define PORTC_PIN7_INITIAL_VALUE      LOW

//PORTD
#define PORTD_PIN0_INITIAL_VALUE      LOW
#define PORTD_PIN1_INITIAL_VALUE      LOW
#define PORTD_PIN2_INITIAL_VALUE      LOW
#define PORTD_PIN3_INITIAL_VALUE      LOW
#define PORTD_PIN4_INITIAL_VALUE      LOW
#define PORTD_PIN5_INITIAL_VALUE      LOW
#define PORTD_PIN6_INITIAL_VALUE      LOW
#define PORTD_PIN7_INITIAL_VALUE      LOW

#endif /* DIO_CONFIG_H_ */
