#ifndef DIO_PRIVATE_H_
#define DIO_PRIVATE_H_

#define INPUT       0
#define OUTPUT      1

#define FLOATING    0
#define PULL_UP     1

#define LOW         0
#define HIGH        1

#define CONC(B7,B6,B5,B4,B3,B2,B1,B0)           CONC_HELPER(B7,B6,B5,B4,B3,B2,B1,B0)
#define CONC_HELPER(B7,B6,B5,B4,B3,B2,B1,B0)    (0b##B7##B6##B5##B4##B3##B2##B1##B0)

#define PORTA_DIRECTION   CONC(PORTA_PIN7_DIRECTION, PORTA_PIN6_DIRECTION, PORTA_PIN5_DIRECTION, PORTA_PIN4_DIRECTION, PORTA_PIN3_DIRECTION, PORTA_PIN2_DIRECTION, PORTA_PIN1_DIRECTION, PORTA_PIN0_DIRECTION)
#define PORTB_DIRECTION   CONC(PORTB_PIN7_DIRECTION, PORTB_PIN6_DIRECTION, PORTB_PIN5_DIRECTION, PORTB_PIN4_DIRECTION, PORTB_PIN3_DIRECTION, PORTB_PIN2_DIRECTION, PORTB_PIN1_DIRECTION, PORTB_PIN0_DIRECTION)
#define PORTC_DIRECTION   CONC(PORTC_PIN7_DIRECTION, PORTC_PIN6_DIRECTION, PORTC_PIN5_DIRECTION, PORTC_PIN4_DIRECTION, PORTC_PIN3_DIRECTION, PORTC_PIN2_DIRECTION, PORTC_PIN1_DIRECTION, PORTC_PIN0_DIRECTION)
#define PORTD_DIRECTION   CONC(PORTD_PIN7_DIRECTION, PORTD_PIN6_DIRECTION, PORTD_PIN5_DIRECTION, PORTD_PIN4_DIRECTION, PORTD_PIN3_DIRECTION, PORTD_PIN2_DIRECTION, PORTD_PIN1_DIRECTION, PORTD_PIN0_DIRECTION)

#define PORTA_INITIAL_VALUE   CONC(PORTA_PIN7_INITIAL_VALUE, PORTA_PIN6_INITIAL_VALUE, PORTA_PIN5_INITIAL_VALUE, PORTA_PIN4_INITIAL_VALUE, PORTA_PIN3_INITIAL_VALUE, PORTA_PIN2_INITIAL_VALUE, PORTA_PIN1_INITIAL_VALUE, PORTA_PIN0_INITIAL_VALUE)
#define PORTB_INITIAL_VALUE   CONC(PORTB_PIN7_INITIAL_VALUE, PORTB_PIN6_INITIAL_VALUE, PORTB_PIN5_INITIAL_VALUE, PORTB_PIN4_INITIAL_VALUE, PORTB_PIN3_INITIAL_VALUE, PORTB_PIN2_INITIAL_VALUE, PORTB_PIN1_INITIAL_VALUE, PORTB_PIN0_INITIAL_VALUE)
#define PORTC_INITIAL_VALUE   CONC(PORTC_PIN7_INITIAL_VALUE, PORTC_PIN6_INITIAL_VALUE, PORTC_PIN5_INITIAL_VALUE, PORTC_PIN4_INITIAL_VALUE, PORTC_PIN3_INITIAL_VALUE, PORTC_PIN2_INITIAL_VALUE, PORTC_PIN1_INITIAL_VALUE, PORTC_PIN0_INITIAL_VALUE)
#define PORTD_INITIAL_VALUE   CONC(PORTD_PIN7_INITIAL_VALUE, PORTD_PIN6_INITIAL_VALUE, PORTD_PIN5_INITIAL_VALUE, PORTD_PIN4_INITIAL_VALUE, PORTD_PIN3_INITIAL_VALUE, PORTD_PIN2_INITIAL_VALUE, PORTD_PIN1_INITIAL_VALUE, PORTD_PIN0_INITIAL_VALUE)

#endif /* DIO_PRIVATE_H_ */